---
name: CI Pipeline

on:
  push:
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

env:
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
  MAVEN_SETTINGS: ${{ github.workspace }}/settings.xml

jobs:
  validate:
    name: Validate Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Validate Maven project
        run: mvn validate -s settings.xml

      - name: Check dependency tree
        run: mvn dependency:tree -s settings.xml

  test:
    name: Test (Java ${{ matrix.java-version }})
    runs-on: ubuntu-latest
    needs: validate

    strategy:
      matrix:
        java-version: [21, 22, 23]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean project
        run: mvn clean -s settings.xml

      - name: Compile project
        run: mvn compile -s settings.xml

      - name: Compile test sources
        run: mvn test-compile -s settings.xml

      - name: Run unit tests
        run: mvn test -s settings.xml

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always() && hashFiles('target/surefire-reports/*.xml') != ''
        with:
          name: Test Results (Java ${{ matrix.java-version }})
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() && (hashFiles('target/surefire-reports/**') != '' || hashFiles('target/site/**') != '')
        with:
          name: test-results-java-${{ matrix.java-version }}
          path: |
            target/surefire-reports/
            target/site/
          retention-days: 30

  baseline-tests:
    name: Baseline Tests (Java ${{ matrix.java-version }})
    runs-on: ubuntu-latest
    needs: validate

    strategy:
      matrix:
        java-version: [21, 22, 23]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run baseline tests
        run: |
          mkdir -p target/baseline-results
          mvn clean test -Pbaseline-tests -s settings.xml

      - name: Upload baseline test results
        uses: actions/upload-artifact@v4
        if: always() && (hashFiles('target/baseline-results/**') != '' || hashFiles('target/surefire-reports/**') != '')
        with:
          name: baseline-results-java-${{ matrix.java-version }}
          path: |
            target/baseline-results/
            target/surefire-reports/
          retention-days: 30

  performance-tests:
    name: Performance Tests (Java 21)
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run performance tests
        run: mvn clean test -Pperformance-tests -s settings.xml

      - name: Upload performance test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results
          path: |
            target/surefire-reports/
          retention-days: 30

  build:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: [test, baseline-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean and package
        run: mvn clean package -DskipTests -s settings.xml

      - name: Verify package contents
        run: |
          echo "=== JAR file ==="
          ls -la target/*.jar
          echo "=== Dependencies ==="
          ls -la target/lib/
          echo "=== JAR contents ==="
          jar tf target/javamail4ews.jar | head -20

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/javamail4ews.jar
            target/lib/
          retention-days: 90

      - name: Upload Maven site
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: maven-site
          path: target/site/
          retention-days: 30

  # security-scan:
  #   name: Security Scan
  #   runs-on: ubuntu-latest
  #   needs: validate
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Set up JDK 21
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: '21'
  #         distribution: 'temurin'
  #         settings-path: ${{ github.workspace }}
  #
  #     - name: Cache Maven dependencies
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.m2/repository
  #         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-maven-
  #
  #     - name: Run OWASP dependency check
  #       run: mvn dependency-check:check -s settings.xml
  #
  #     - name: Upload security reports
  #       uses: actions/upload-artifact@v4
  #       if: always() && hashFiles('target/security-reports/**') != ''
  #       with:
  #         name: security-reports
  #         path: target/security-reports/
  #         retention-days: 90
  #
  # Note: Security scan temporarily disabled due to NVD API rate limiting issues
  # Can be re-enabled once NVD API access is properly configured